/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Thu Feb 15 16:26:04 2018. */

#ifndef PB_ENVIRONMENT_PB_H_INCLUDED
#define PB_ENVIRONMENT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Environment {
    double temperature;
    double humidity;
    double pressure;
/* @@protoc_insertion_point(struct:Environment) */
} Environment;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Environment_init_default                 {0, 0, 0}
#define Environment_init_zero                    {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Environment_temperature_tag              1
#define Environment_humidity_tag                 2
#define Environment_pressure_tag                 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t Environment_fields[4];

/* Maximum encoded size of messages (where known) */
#define Environment_size                         27

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ENVIRONMENT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
