/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SRC_ENVIRONMENT_PB_H_INCLUDED
#define PB_SRC_ENVIRONMENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Environment { 
    double temperature; 
    double humidity; 
    double pressure; 
} Environment;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Environment_init_default                 {0, 0, 0}
#define Environment_init_zero                    {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Environment_temperature_tag              1
#define Environment_humidity_tag                 2
#define Environment_pressure_tag                 3

/* Struct field encoding specification for nanopb */
#define Environment_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   temperature,       1) \
X(a, STATIC,   REQUIRED, DOUBLE,   humidity,          2) \
X(a, STATIC,   REQUIRED, DOUBLE,   pressure,          3)
#define Environment_CALLBACK NULL
#define Environment_DEFAULT NULL

extern const pb_msgdesc_t Environment_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Environment_fields &Environment_msg

/* Maximum encoded size of messages (where known) */
#define Environment_size                         27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
